#!/usr/bin/env python3
""" Soluton of minion_game"""


# VOWELS = ['A', 'E', 'I', 'O', 'U']


# def stuart_score(string):
#     """Returnt score of Stuart"""
#     score = 0
#     for index in range(len(string)):
#         new_string = string[index:]
#         if string[index] not in VOWELS:
#             score += len(new_string)
#     return score
# 
# 
# def kevin_score(string):
#     """Return score of Stuart"""
#     score = 0
#     for index in range(len(string)):
#         new_string = string[index:]
#         if string[index] in VOWELS:
#             score += len(new_string)
#     return score


def minion_game(string):
    """return name of winner"""
    vowels = 'AEIOU'
    k_score = 0
    s_score = 0

    for index in range(len(string)):
        if string[index] in vowels:
            k_score += len(string) - index
        else:
            s_score += len(string) - index

    if k_score > s_score:
        print("Kevin", k_score)
    if k_score < s_score:
        print("Stuart", s_score)
    if k_score == s_score:
        print("Draw")


def main():
    """main function"""
    # str_input = input()
    str_input = "ADFADZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPQPQPQPQPPQPQPQPQPQPQPQPPQPQPQPQPPQPQPQPQPPQPQPQPQPPQPQPQPQPQPQPWWWWWWWWMMMMMMWMMWMMWMWMWMMWWMWMMQMMQMQMQMQMMQMQMWMMWMWMQMMWMQMWMQMQWMMQWMWQMQMMQQWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWUEEEEEEEEEEEEEEEEEEEEEEEEETEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEERRRRRRRRRRRRRRRRRRRRQWERTYUIOPWFQTEFDADAEERQWPTOWETIWITQWETIWQTIQWTGQWGJASGJADSZXCVCNVFCMDFAKEPREURHQREHQEWRTQAZWSXEDCRFVTGBYHNUJMIKLOPPPPPPPPPPPPPPPPPPPPPAAQQWEEQQQQQQQWWWWWWAAAAAAAAAAAAAAAAAAAAAAAAAAFHDJSAFSAJKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKEUIIIASDLJRADFADZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPQPQPQPQPPQPQPQPQPQPQPQPPQPQPQPQPPQPQPQPQPPQPQPQPQPPQPQPQPQPQPQPWWWWWWWWMMMMMMWMMWMMWMWMWMMWWMWMMQMMQMQMQMQMMQMQMWMMWMWMQMMWMQMWMQMQWMMQWMWQMQMMQQWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWUEEEEEEEEEEEEEEEEEEEEEEEEETEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEERRRRRRRRRRRRRRRRRRRRQWERTYUIOPWFQTEFDADAEERQWPTOWETIWITQWETIWQTIQWTGQWGJASGJADSZXCVCNVFCMDFAKEPREURHQREHQEWRTQAZWSXEDCRFVTGBYHNUJMIKLOPPPPPPPPPPPPPPPPPPPPPAAQQWEEQQQQQQQWWWWWWAAAAAAAAAAAAAAAAAAAAAAAAAAFHDJSAFSAJKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKEUIIIASDLJR"
    minion_game(str_input)


if __name__ == "__main__":
    main()
